###
GET http://localhost:5132/pessoas/bac2d3be-1569-4b68-8bb7-bc0fc6765389

###
GET http://localhost:5132/pessoas?t=node

###
GET http://localhost:5132/pessoas

###
POST http://localhost:5132/pessoas
Content-Type: application/json

{
    "nome": "Mario",
    "Apelido": "Do Armario",
    "Nascimento": "1985-13-09",
    "stack" : ["C#", "Node", "Oracle"]
}

###
POST http://localhost:5132/pessoas
Content-Type: application/json

{
    "nome": "Mario",
    "Apelido": "Do Armario",
    "Nascimento": "1985-13-09"
}