version: "3.9"
services:
  api1: &api # API - Instância 01
    build:
      context: .
      dockerfile: Srv/Dockerfile
    hostname: api1
    depends_on:
      - db
    expose:
      - "80"
    deploy:
      resources:
        limits:
          cpus: "0.20"
          memory: "0.375GB"

  api2: # API - Instância 02
    <<: *api
    hostname: api2

  nginx: # Load Balancer
    image: nginx:latest
    volumes:
      - ./configs/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api1
      - api2
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: "0.5GB"
  
  db:
    image: postgres:16-alpine
    hostname: db
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=rinha
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    deploy:
      resources:
        limits:
          cpus: '0.15'
          memory: '0.4GB'

  pgadmin: #Apenas para debug
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
      # PGADMIN_LISTEN_PORT: 5050
    ports:
      - "5555:80"
    depends_on:
      - db
