version: "3.9"
services:
  api1: &api # API - Instância 01
    image: api
    hostname: api1
    depends_on:
      - db
      - nats
    expose:
      - "80"
    deploy:
      resources:
        limits:
          cpus: "0.20"
          memory: "0.375GB"

  api2: # API - Instância 02
    <<: *api
    hostname: api2

  nginx: # Load Balancer
    image: nginx:latest
    volumes:
      - ./configs/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api1
      - api2
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: "0.5GB"
  
  nats: # Jobs
    image: nats:alpine
    ports:
       - "4222:4222"
    deploy:
      resources:
        limits:
          cpus: "0.10"
          memory: "0.250GB"

  db: # Banco de dados
    image: mysql:8.1
    ports:
      - '3306:3306'
    restart: on-failure
    environment:
      - MYSQL_SERVER=db
      - MYSQL_DATABASE=db
      - MYSQL_ROOT_PASSWORD=asd09u123ncv
    deploy:
      resources:
        limits:
          cpus: "0.75"
          memory: "1.5GB"

  myAdmin:
    image: phpmyadmin:5.2.1
    ports:
      - 8081:8081
    links:
      - db
    environment:
      PMA_HOST: 'db'
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    depends_on:
      - db